eureka:
#  instance:
#    #hostname: gomyck-auth.com
#    #instance-id: ${spring.application.name}-@project.version@-${spring.cloud.client.ip-address}:${server.port}
#    #是否以IP方式注册, 如果是否的话, 在通讯时会用hostname作为请求地址
#    #prefer-ip-address: true
#    #心跳时间
#    lease-renewal-interval-in-seconds: 5
#    #服务时效时间 (这个值要比心跳时间大, 如果上次心跳到下次心跳时间超过这个值, eureka注册中心将会下线改服务)
#    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka,http://127.0.0.1:8081/eureka
server:
  port: 8091

spring:
  application:
    name: provider