eureka:
  instance:
    preferIpAddress: false
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 1
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 2
  client:
    healthcheck:
      # 开启健康检查 （需要spring-boot-starter-actuator依赖）
      enabled: true
    serviceUrl:
      defaultZone: http://servermaster:8080/eureka,http://serversave:8081/eureka
server:
  port: 8070
spring:
  application:
    name: client